[package]
name = "mips_compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structure = "0.1"
clap = { version = "3.0.14", features = ["derive"] }
lazy_static = "1.4.0"
mut_static = "5.0.0"
